version: '3'
services:
    mysql:
      image: mysql:5.7.18
      container_name: mysql-container
      restart: always
      volumes:
        - /opt/mysql/data:/var/lib/mysql
        - /opt/mysql/mysqld:/var/run/mysqld
        - /opt/mysql/conf/my.cnf:/etc/my.cnf
      ports:
        # 主机：容器
        - "3306:3306"
      environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: openim
          MYSQL_USER: openim
          MYSQL_PASSWORD: openim

